BRUSH_TOOL = "BRUSH"
FILL_TOOL = "FILL"
RECT_TOOL = "RECT"
CIRCLE_TOOL = "CIRCLE"

IMPORT = "IMPORT"
EXPORT = "EXPORT"

ACTION_BACK = "ACTION_BACK"
ACTION_FORWARD = "ACTION_FORWARD"

LINE_SIZE = [5, 15, 30]