import configs.colors


SCREEN_SIZE = (1200, 800)

BG_COLOR = configs.colors.WHITE

FPS = 1200

SCREENSHOT_BOX = ...

CANVAS_BORDERS = (SCREEN_SIZE[0] - 100, SCREEN_SIZE[1])

SAVE_SCREENSHOT_PATH = ...