import configs.colors


SCREEN_SIZE = (1200, 800)

BG_COLOR = configs.colors.WHITE

FPS = 1200

CANVAS_BORDERS = (SCREEN_SIZE[0] - 100, SCREEN_SIZE[1])

SCREENSHOT_BOX = CANVAS_BORDERS

IMPORT_SCREENSHOT_PATH = None
EXPORT_SCREENSHOT_PATH = "screenshots/"

CANVAS_CURRENT_SCREEN_NEXT = "next"
CANVAS_CURRENT_SCREEN_PREVIOUS = "previous"