import configs.colors


WINDOW_SIZE = (1200, 800)
ZERO_COORDINATES = (0, 0)
MAIN_COLOR_SHOW_COORDINATES = (25, 525, 50, 25)
MAIN_INSTRUMENT_SHOW_COORDINATES = (25, 450)
GUI_REGION_POSITION = (WINDOW_SIZE[0] - 100, 0)

BG_COLOR = configs.colors.WHITE

FPS = 1200

CANVAS_SIZE = (WINDOW_SIZE[0] - 100, WINDOW_SIZE[1])
CANVAS_BOX = (0, 0, CANVAS_SIZE[0], CANVAS_SIZE[1])
SCREENSHOT_BOX = CANVAS_SIZE
GUI_REGION_SIZE = (100, 1200)

APPROVED_CANVAS_ACTIONS = "APPROVED"
UNAPPROVED_CANVAS_ACTIONS = "UNAPPROVED"